name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  # Job para executar os testes
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2
        
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar testes
        run: |
          python -m unittest discover -s tests

  # Job para empacotamento
  build:
    runs-on: ubuntu-latest
    needs: test  
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2
        
      - name: Empacotar a aplicação
        run: |
          python setup.py sdist bdist_wheel  # Ajuste conforme necessário

  notify:
    runs-on: ubuntu-latest
    needs: build  
    steps:
      - name: Enviar e-mail de notificação
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          python sendEmail.py
